### ISSUE TITLE
Formatting output

### ISSUE THREAD

**Issue by zuliandres** [merlinthemagic/MTS#12]
Thank you for providing this which is a great way to learn, and yes it has some security concerns that one has to address. I was wondering if there is a way to address output formatting, in a way that it might appear more organized. Since you have experience I thought maybe you had some ideas. 
Thanks

**Comment by merlinthemagic** [comment]
Hi @zuliandres im glad you found it useful. It's not much fun building tools that no one give you feedback on :). 
In regards to formatting I assume you are talking about the shell modules and not the headless browser output.

The truth is that MTS has a sister project which extends its functionality and provides standard object returns for a few hundred common commands across any OS and shell type. The idea was that programmers should not have to learn how to implement i.e. vlan on an interface or know the syntax for getting i.e. ARP or routing table of a device. He or she would just pass a shellObj and appropriate arguments to a class that deals with the specific OS syntax of i.e. setting up a vLan sub-interface (I come from the network engineering world, so most of the classes are centered around networking.).

I am not planning to make that project public because it forms the basis of an API I charge for and it would be of little interest to a casual user. However, if you are interested i could setup a skeleton repository that shows you how the classes are structured. It would provide you a pattern to follow when adding a new standard function.

**Comment by zuliandres** [comment]
That sounds interesting, I am a bit new to this so any other pointers would be much appreciated.
Let me know!

**Comment by merlinthemagic** [comment]
How would you like to change the output format?

**Comment by zuliandres** [comment]
I figured out a way to turn some of the ANSI formatting to html5 so I think that works for now. DO you have any examples for websites that use this tool online?

**Comment by merlinthemagic** [comment]
Hi,

I'm a bit lost, I'm not sure which tool and in which context. Could you provide a code example?

**Comment by zuliandres** [comment]
i am basically trying to give users a way to interact with an Ubuntu user account. I found tools like Webmin, Usermin to give this restricted access so they can test a mesh network testbed. I think for executing some commands for network testing they should be able to use a shell interface. This is the reason why I wanted to use your tool. Right know I am just testing different options, and I found that when running commands through your tool, there are some irregularities with what the actual OS shell is like. I would appreciate if you would share your thoughts. Thank you again

**Comment by merlinthemagic** [comment]
Sorry for the late reply.

From what i gather you are building an app that will let users interact with a Ubuntu system through a web interface and you want the ability to execute shell commands through that interface.

First question: 
"...I found that when running commands through your tool, there are some irregularities with what the actual OS shell is like..". 
Could you provide a code example? If issuing a command on the console deviates from what you get through MTS i would like to know.

Second question:
Do you require the shell resource to live beyond the life of a single http request? or have you implemented a webSocket server? (both are possible).

If you have a code repo i can look at it will make things so much easier and less abstract.

**Comment by merlinthemagic** [comment]
Do you still require help?
