### ISSUE TITLE
License

### ISSUE THREAD

**Issue by darkain** [merlinthemagic/MTS#41]
Could you provide a license file for this code, so we know what it can/cannot be used for? I'm interested in possibly using this for a BSD related project, but everything must be explicitly licensed appropriately or else it cannot be included in the project.

**Comment by merlinthemagic** [comment]
Done.

Released under LGPL.

**Comment by darkain** [comment]
Thanks!

**Comment by merlinthemagic** [comment]
FYI. I have been sitting on a a new version of MTS (MHIT), different internal structure, fewer dependencies, new namespace, but same shell interface.

I have not released it because i have not had time to do the documentation. Once you have decided if you will be using MTS, check back and see if MHIT is in the public repos.

Everyone likes fewer dependencies and more stability.

**Comment by darkain** [comment]
Will do! I'm actively following this project now and will be testing it out for my system over the next few months.
